### ISSUE TITLE
What form of backend cms would we like to use and how will we implement it?

### ISSUE THREAD

**Issue by jaruesink** [jaruesink/ID-C#1]
something to discuss with Coulton?

**Comment by coulton** [comment]
It's going to be a blog... So maybe WordPress, or Anchor CMS? I've developed for both.

**Comment by jaruesink** [comment]
I like wordpress better. Derek was mentioning Django CMS which looked pretty good. But this is all y'all. I'm not very practiced with that part of it. Do you think it will be difficult to hook this in?

**Comment by coulton** [comment]
I have a lot of experience in WordPress. It would be pretty easy to set up. I've never worked with Django CMS.

**Comment by jaruesink** [comment]
alright let's do wordpress. When do y'all think get that done by? I know how to install wordpress, so I'll be able to edit locally also. If I need to get a host set up, I don't mind paying for that already. @djrobotfreak you good with that?

**Comment by jaruesink** [comment]
also might check out this dev bootstrap theme https://drive.google.com/folderview?id=0B5teN9F_jc5uN0hianN0RXk5NWc&usp=sharing so see if it's something worth starting with

**Comment by djrobotfreak** [comment]
Yea wordpress is fine, I dont know that much django. It's probably simpler.
